### ISSUE TITLE
Error with gremlin version 3.2.9

### ISSUE THREAD

**Issue by andry85mae** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#23]
Hello

i try to install the new version of gremlin (3.2.9) for use the gremlin fluent api.
When i try to execute the code , it give me an error.

Exists a new implementation or example?

Thanks

Andrea

**Comment by LuisBosquez** [comment]
hello @andry85mae, can you please provide an example of the error you're getting?

**Comment by donniekerr** [comment]
Does Cosmos support this latest version https://www.npmjs.com/package/gremlin 3.4.4 in 2020? If not, what do I need to use?  The example links to npm gremlin, which does not use the same code as this example.

**Comment by lukiffer** [comment]
Not sure the status of this repository, but the "current" MSFT docs point here. @LuisBosquez When using the `gremlin@3.4.4` npm package, it appears that the remote either doesn't support or isn't expecting GraphSON v3:

```
        - ResponseError: Server error:

        ActivityId : 0991f445-8fc6-486f-b2e4-f1b636f8225c
        ExceptionType : GraphMalformedException
        ExceptionMessage :
        	Gremlin Malformed Request: GraphSON v3 IO is not supported.
        	GremlinRequestId : 0991f445-8fc6-486f-b2e4-f1b636f8225c
        	Context : global
        	GraphInterOpStatusCode : MalformedRequest
        	HResult : 0x80131500
         (498)
```

Moreover, to @andry85mae's point, the documentation from the TinkerPop project itself recommends against using the `client.submit()` method and is maintaining this for legacy compatibility only – the fluent API is preferred.

> TinkerPop does not recommend submitting script-based requests and generally continues to support this feature for legacy reasons and corner use cases which are still not completely addressed by the Gremlin language. Please consider using bytecode-based requests instead when possible

Can we get specifics on a few things?:

- Should the Cosmos DB driver support this version of the Gremlin client?
- If not, what version is supported?
- If so, what needs to be done to make it work?
- For both of the above, please document this in the README
- Are there plans to update this to example to the fluent API as it's significantly easier to work with than string manipulation and "parameterised" queries?

**Comment by lukiffer** [comment]
After a little bit more digging, it appears it may be an incompatibility with the Cosmos DB driver not supporting bytecode-type IO.

```
ExceptionType : GraphMalformedException
ExceptionMessage :
	Gremlin Malformed Request: Unsupported request operation: 'bytecode'.
	GremlinRequestId : c18a6d7e-6704-4e02-b66f-1f39ab9caa82
	Context : global
	GraphInterOpStatusCode : MalformedRequest
	HResult : 0x80131500
 (498)
```

Looks like we might be stuck with the `client.submit()` method until the support is added.

**Comment by ncausey** [comment]
There is feedback here, and it looks like this was supposed to be done earlier this year. Still not here unfortunately https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/33632779-support-gremlin-bytecode-to-enable-the-fluent-api

**Comment by Adityagrao** [comment]
Hope this is fixed soon

**Comment by donniekerr** [comment]
I gave up. I wasn't seeing any progress on this api.   I ended up building my own with GraphQL and two collections: nodes and links.  Then I simply write graphQL queries.  Cosmos SQL API, not Gremlin.

**Comment by odeliat** [comment]
Was this fix? Or going to be fix? (I'm getting the same error too V.3.5.1)

**Comment by questsin** [comment]
still not fixed.


const client = new gremlin.driver.Client(
    config.endpoint, {
        authenticator,
        traversalsource: "g",
        rejectUnauthorized: true,
        mimeType: "application/vnd.gremlin-v2.0+json"
    }
);

const traversal = gremlin.process.AnonymousTraversalSource.traversal;
const DriverRemoteConnection = gremlin.driver.DriverRemoteConnection;
const g = traversal().withRemote(client);

// client.submit("g.V()", function (err, results) {
// }).then(function (result) {
//     console.log("Result: %s\n", JSON.stringify(result));
// });

async function main() {
  const names = await g.V().hasLabel('person').values('name').toList();
  console.log(names);
}
main();

**Comment by chris-ux** [comment]
![image](https://user-images.githubusercontent.com/1118231/155389857-4cd511f2-9893-4b56-aa8f-8243a2b899b6.png)
![image](https://user-images.githubusercontent.com/1118231/155390355-e0f3e353-4243-4feb-bfae-edeb8c2f211e.png)

**Comment by olivertowers** [comment]
Not reproducible with latest sample + gremlin-javascript version 3.4.13

**Comment by igord** [comment]
I just reproduced it with 3.6.1. 
And it is still open: https://feedback.azure.com/d365community/idea/aa287df8-0e25-ec11-b6e6-000d3a4f0858
